name: Automated API tests using Newman

on: push

jobs:
  automated-api-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Newman
        run: npm install -g newman newman-reporter-html
      - name: Run API tests with Newman and generate report
        run: |
          newman run "https://api.getpostman.com/collections/30004335-98fcaed5-4ec9-4beb-ba83-50cfbaccc8c1?apikey=${{ secrets.POSTMAN_API_KEY }}" \
          --environment "https://api.getpostman.com/environments/30004335-405e48ed-6f85-48e8-8621-78490293e471?apikey=${{ secrets.POSTMAN_API_KEY }}" \
          --reporters cli,html \
          --reporter-html-export "newman-report.html"
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman-report.html
