name: Automated API tests using Newman

on: 
    workflow_dispatch:
    push:

jobs:
  automated-api-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Newman
        run: npm install -g newman
      - name: Run API tests and generate report
        run: |
          newman run "30004335-98fcaed5-4ec9-4beb-ba83-50cfbaccc8c1" -e "30004335-405e48ed-6f85-48e8-8621-78490293e471" --reporters cli,html --reporter-html-export "newman/newman-report.html"
      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: postman-api-test-report
          path: newman/newman-report.html
